spring:
  application:
    name: spring-boot-service
  jackson:
    default-property-inclusion: non_empty

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    propagation:
      produce: w3c, b3, b3_multi
      consume: b3, w3c, b3_multi
    baggage:
      remote-fields: requestId
      correlation:
        fields: requestId
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        resource-attributes:
          "service.name": ${spring.application.name}
          "app_name": ${spring.application.name}
logging:
  pattern:
    level: "%5p [${spring.application.name:},traceID=%X{traceId:-},%X{spanId:-}]"
  file:
    name: /tmp/${spring.application.name}.log

##grafana:
#  otlp:
#    debug-logging: false
#    on-prem:
#      endpoint: http://localhost:4317
#      protocol: grpc