apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    jsonData:
      httpMethod: GET

  - name: elasticsearch-v7-filebeat
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    jsonData:
#      index: '[filebeat-]YYYY.MM.DD'
      interval: Daily
      timeField: '@timestamp'
      logMessageField: message
      logLevelField: fields.level
      dataLinks:
        - datasourceUid: tempo # Target UID needs to be known
          field: traceID
          url: '$${__value.raw}'

  - name: Tempo
    type: tempo
    access: browser
    orgId: 1
    uid: tempo
    url: http://tempo:3200
    isDefault: true
    editable: true
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: 'prometheus'

  - name: Loki
    type: loki
    access: browser
    orgId: 1
    uid: loki
    url: http://loki:3100
    isDefault: false
    editable: true
    jsonData:
      derivedFields:
        - datasourceName: Tempo
          matcherRegex: "traceID=(\\w+)"
          name: traceId_field
          url: '$${__value.raw}'
          datasourceUid: tempo
        - datasourceName: Tempo
          matcherRegex: '"[traceid|traceId]":.+"(.*?)"'
          name: traceId_json
          url: '$${__value.raw}'
          datasourceUid: tempo
        - datasourceName: Tempo
          matcherRegex: '/v1/.*?:\s(.*?)\s'
          name: trace_logs
          url: '$${__value.raw}'
          datasourceUid: tempo
