server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: http://loki:3100/api/prom/push

scrape_configs:
#  - job_name: system
#    pipeline_stages:
#      - docker:
#    static_configs:
#      - targets:
#          - localhost
#        labels:
#          job: varlogs
#          host: yourhost
#          __path__: /var/log/*.log

  - job_name: flask-service
    pipeline_stages:
      - docker:
    static_configs:
      - targets:
          - localhost
        labels:
          job: flask-service
          host: localhost
          __path__: /tmp/simple-flask-python-server.log


  - job_name: payment-service
    pipeline_stages:
      - docker:
    static_configs:
      - targets:
          - localhost
        labels:
          job: payment-service
          host: localhost
          __path__: /tmp/payment-service.log
