global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
#  - job_name: 'tempo'
#    static_configs:
#      - targets: [ 'tempo:3200' ]
#  - job_name: 'opentelemetry-collector'
#    static_configs:
#      - targets: [ 'otel-collector:8888' ]
#  - job_name: 'payment-service'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['payment-service:8080']
#  - job_name: 'simple-flask-python-server'
#    static_configs:
#      - targets: ['python-service:8091']
  - job_name: 'opentelemetry'
    static_configs:
      - targets: ['otel-collector:1234']
